### ISSUE TITLE
example not working in python 3.7

### ISSUE THREAD

**Issue by fitasovmd** [jgargallo/aiohttp-paginator#1]
C:/Users/fitasovmd/.PyCharmCE2018.3/config/scratches/scratch_96.py:28: DeprecationWarning: verify_ssl is deprecated, use ssl=False instead
  conn = aiohttp.TCPConnector(family=socket.AF_INET, verify_ssl=False)
C:/Users/fitasovmd/.PyCharmCE2018.3/config/scratches/scratch_96.py:34: RuntimeWarning: coroutine '_Paginator.__aiter__' was never awaited
Coroutine created at (most recent call last)
  File "C:/Users/fitasovmd/.PyCharmCE2018.3/config/scratches/scratch_96.py", line 42, in <module>
    loop.run_until_complete(main())
  File "C:\Users\fitasovmd\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 560, in run_until_complete
    self.run_forever()
  File "C:\Users\fitasovmd\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 528, in run_forever
    self._run_once()
  File "C:\Users\fitasovmd\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1756, in _run_once
    handle._run()
  File "C:\Users\fitasovmd\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:/Users/fitasovmd/.PyCharmCE2018.3/config/scratches/scratch_96.py", line 34, in main
    async for response in session.pget(pag_helper, buffer_size=1, keep_order=False):
  async for response in session.pget(pag_helper, buffer_size=1, keep_order=False):
Traceback (most recent call last):
  File "C:/Users/fitasovmd/.PyCharmCE2018.3/config/scratches/scratch_96.py", line 42, in <module>
    loop.run_until_complete(main())
  File "C:\Users\fitasovmd\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "C:/Users/fitasovmd/.PyCharmCE2018.3/config/scratches/scratch_96.py", line 34, in main
    async for response in session.pget(pag_helper, buffer_size=1, keep_order=False):
TypeError: 'async for' received an object from __aiter__ that does not implement __anext__: coroutine

Process finished with exit code 1

**Comment by jgargallo** [comment]
Can you try now?
